config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :courses_categories
  # resources :courses
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
end

app/views/shared/_footer.html.erb
<footer class="row p-3 m-0 bg-light text-center border-top">
  <div class="col-sm-12 col-md-6 m-0 p-0">
    <p>&copy;Copyright 2022. Developed and Designed by Clayton Siby.</p>
  </div>
  <div class="col-sm-12 col-md-6 m-0 p-0">
    <p>All rights reserved.</p>
  </div>
</footer>

app/views/shared/_hero.html.erb
<section class="hero_section">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item img-fluid active">
        <%= image_tag 'engineering.jpg', class: 'd-block w-100 carousel_image' %>
        <div class="carousel-caption text-left text-light">
          <h1>Do you have what it takes to be a Software Engineer!</h1>
          <p>Gain the skills you need to get hired by global companies or start your own Software business.</p>
        </div>
      </div>
      <div class="carousel-item img-fluid">
        <%= image_tag 'coding_lecture.jpg', class: 'd-block w-100 carousel_image' %>
        <div class="carousel-caption text-light">
          <h2>Get unlimited access to courses and material essential to be a professional Software Engineer.</h2>
          <p>All you need is the willingness to learn and grow.</p>
        </div>
      </div>
      <div class="carousel-item img-fluid">
        <%= image_tag 'one_on_one_lectures.jpg', class: 'd-block w-100 carousel_image' %>
        <div class="carousel-caption text-light">
          <h3>Get One-On-One live sessions with industry experts in the Industry.</h3>
          <p>We offer mentorship opportunities to help you profoundly develop both technical and soft skills to help you succeed in the Tech industry  </p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container p-0">
    <a class="navbar-brand py-1" href="/">
      <%= image_tag('logo.png', class: 'align-middle logo') %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto px-2">
        <li class="nav-item">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About Us</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact Us</a>
        </li>
        <% if current_user.nil? %>
          <li class="nav-item">
            <button type="button" class="btn btn-sm btn-default border mx-3">
              <%= link_to 'Get Started', new_user_session_path, class: 'nav-link' %>
            </button>
          </li>
        <% end %>
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to current_user.username, edit_user_registration_path, class: "dropdown-item", title: 'Click to edit profile' %>
              </li>
              <li>
                <%= button_to 'SignOut', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>