config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :courses_categories
  # resources :courses
  resources :categories
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
end

app/helpers/courses_categories_helper.rb
module CoursesCategoriesHelper
end

app/views/courses_categories/_form.html.erb
<%= form_with(model: courses_category) do |form| %>
  <% if courses_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courses_category.errors.count, "error") %> prohibited this courses_category from being saved:</h2>

      <ul>
        <% courses_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses_categories/edit.html.erb
<h1>Editing Courses Category</h1>

<%= render 'form', courses_category: @courses_category %>

<%= link_to 'Show', @courses_category %> |
<%= link_to 'Back', courses_categories_path %>

app/views/courses_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses_categories.each do |courses_category| %>
      <tr>
        <td><%= link_to 'Show', courses_category %></td>
        <td><%= link_to 'Edit', edit_courses_category_path(courses_category) %></td>
        <td><%= link_to 'Destroy', courses_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courses Category', new_courses_category_path %>

app/views/courses_categories/new.html.erb
<h1>New Courses Category</h1>

<%= render 'form', courses_category: @courses_category %>

<%= link_to 'Back', courses_categories_path %>

app/views/courses_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_courses_category_path(@courses_category) %> |
<%= link_to 'Back', courses_categories_path %>